version: '2'  
services:  
  nginx:
    image: nginx:alpine
    container_name: nginx_app
    ports:
      - "8000:8000"
    volumes:
      - ./src:/src
      - ./config/nginx:/etc/nginx/conf.d
    depends_on:
      - web
  web:
    build: .
    container_name: web_app
    depends_on:
      - db
    volumes:
      - ./src:/src
    expose:
      - "8000"
    links:
      - redis
  db:
    image: postgres:alpine
    container_name: postgres_db
    ports:
      - "5432:5432"
    
  redis:
    image: redis:alpine
    container_name: redis_app
    ports:
     - '6379:6379'

